version: '3'

services:
  db:
    image: mariadb:latest
    command: --init-file /docker-entrypoint-initdb.d/pdns-schema.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns 
      - MYSQL_PASSWORD=da09c7c92024_
    ports:
      - 3306:3306 
    restart: always
    volumes:
      - /pda-mysql:/var/lib/mysql
      - ./pdns-schema.sql:/docker-entrypoint-initdb.d/pdns-schema.sql:ro
  pdns:
    #build: pdns
    image: pschiffe/pdns-mysql
    hostname: pdns
    restart: always
    depends_on:
      - db
    links:
      - "db:mysql"
    ports:
      - "53:53"
      - "53:53/udp"
      - "9081:8081"
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_dbname=pdns
      - PDNS_gmysql_password=da09c7c92024_
      - PDNS_master=yes
      - PDNS_slave=no 
      - PDNS_api=yes
      - PDNS_disable-syslog = no
      - PDNS_api_key=a035bc96d3dc46ce80675
      - PDNSCONF_API_KEY=a035bc96d3dc46ce80675
      - PDNS_webserver=yes 
      - PDNS_webserver-allow-from=0.0.0.0/0 
      - PDNS_webserver_address=0.0.0.0 
      - PDNS_webserver_password=secret2 
      - PDNS_version_string=anonymous 
      - PDNS_default_ttl=1500 
      - PDNS_allow_notify_from=0.0.0.0 
      - PDNS_allow-axfr-ips=194.69.60.5 

  web_app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "9080:80"
    depends_on:
      - db
    restart: always
    links:
      - db:mysql
      - pdns:pdns
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:da09c7c92024_@db/pdns
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
